services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8765"
    environment:
      - REDIS_ARGS=--requirepass RedisPass032
    volumes:
      - redis_data:/data
    restart: always

  cloudlens-ai:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: cloudlens-ai
    ports:
      - 8000:8000
    depends_on:
      - redis-stack
    environment:
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
      - REDIS_PASSWORD=RedisPass032
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis_data:
